
The function writes to `public.rotation_log` so you can audit each rotation.

---

## One-time setup

1) **GitHub Secrets** (Settings → Secrets and variables → Actions)  
   - `SUPABASE_SERVICE_ROLE_KEY` (service role key from Supabase → Project Settings → API)  
   - `TOTAL_TARGET` (optional)  
   - `CALLIGRAPHY_TARGET` (optional)

2) **Workflow file**  
   Located at `.github/workflows/rotate.yml` (includes retries, summaries, and concurrency).

---

## Manual runs (GitHub Actions)

1. Go to **Actions → Rotate Artworks → Run workflow**.  
2. Inputs:
   - `dry`: `"true"` for a safe test, `"false"` for a live rotation.
   - `total_target`, `calligraphy_target`: leave blank to use secrets/defaults.
3. Open the run → **Summary** shows parameters, JSON payload, HTTP status, and the Supabase response body.

---

## Verify in Supabase

Run in **SQL Editor**:

```sql
-- Live runs only
select ran_at, dry, before_visible, after_visible,
       unarchive_calligraphy_ids, unarchive_other_ids, archive_ids
from public.rotation_log
where dry = false
order by ran_at desc, id desc
limit 10;
